// vue/src/App.vue
<template>
    <div id="app">
        <DxToolbar id="toolbar">
            <DxItem
                widget="dxButton"
                :options="buttonOptions"
                location="before"
            />
        </DxToolbar>
        <DxDrawer
            opened-state-mode="overlap"
            reveal-mode="expand"
            v-model:opened="isDrawerOpen"
            :minSize="37"
            :height="250"
            template="list">
            <template #list>
                <NavigationList
                    @navigated="isDrawerOpen = false"
                />
            </template>
            <div id="view">
                <router-view></router-view>
            </div>
        </DxDrawer>
    </div>
</template>

<script>
import DxDrawer from 'devextreme-vue/drawer';
import DxToolbar, { DxItem } from 'devextreme-vue/toolbar';

import NavigationList from './components/NavigationList.vue';

export default {
    components: {
        DxDrawer,
        DxToolbar,
        DxItem,
        NavigationList
    },
    data() {
      const navigation = [
            { id: 1, text: "Inbox", icon: "message", path: "inbox" },
            { id: 2, text: "Sent Mail", icon: "check", path: "sent-mail" },
            { id: 3, text: "Trash", icon: "trash", path: "trash" },
            { id: 4, text: "Spam", icon: "mention", path: "spam" }
        ];
        return {
            buttonOptions: {
                icon: "menu",
                onClick: () => {
                    this.isDrawerOpen = !this.isDrawerOpen;
                }
            },
            isDrawerOpen: false,
            navigation
        };
    }
};
</script>

<style>
.dx-overlay-content {
    background-color: lightgray;
}
#view {
    margin-left: 10px;
    margin-top: 10px;
}
#toolbar {
    background-color: rgba(191, 191, 191, 0.15);
    padding: 5px 10px;
}
.dx-toolbar-button .dx-button {
    background-color: rgba(191, 191, 191, -0.15);
    border: none;
}
.dx-toolbar-button > .dx-toolbar-item-content {
    margin-left: -7px;
}
.dx-list-item-icon {
    margin-right: 10px;
}
</style>

// angular/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    title = 'getting-started-with-drawer';
    navigation: any[] = [
        { id: 1, text: "Inbox", icon: "message", path: "inbox" },
        { id: 2, text: "Sent Mail", icon: "check", path: "sent-mail" },
        { id: 3, text: "Trash", icon: "trash", path: "trash" },
        { id: 4, text: "Spam", icon: "mention", path: "spam" }
    ];
    isDrawerOpen: boolean = true;
    buttonOptions: any = {
        icon: "menu",
        onClick: () => {
            this.isDrawerOpen = !this.isDrawerOpen;
        }
    }
}
<dx-toolbar id="toolbar">
    <dxi-item 
        widget="dxButton"
        [options]="buttonOptions"
        location="before">
    </dxi-item>
</dx-toolbar>
<dx-drawer
    template="template"
    [height]="250"
    [(opened)]="isDrawerOpen"
    [minSize]="37"
    revealMode="expand"
    openedStateMode="overlap">
    <div *dxTemplate="let data of 'template'">
        <dx-list
            [items]="navigation"
            [width]="200"
            selectionMode="single"
            (onSelectionChanged)="this.isDrawerOpen = false"
            itemTemplate="links">
            <div *dxTemplate="let link of 'links'">
                <a [routerLink]="['/' + link.path]">
                    <div>
                        <div class="dx-list-item-icon-container">
                            <i class="dx-icon dx-list-item-icon dx-icon-{{link.icon}}"></i>
                        </div>
                        <span>{{ link.text }}</span>
                    </div>
                </a>
            </div>
        </dx-list>
    </div>
    <div id="view">
        <router-outlet></router-outlet>
    </div>
</dx-drawer>
